### ISSUE TITLE
Detect existing screens and update DPI configuration

### ISSUE THREAD

**Issue by zedtux** [cassidyjames/dippi#75] opened 2020-01-29 08:03 UTC
I'm running on a 13" MacBook Pro with an external screen and I have a different DPI on both screen so that the content on the laptop looks really small, while it looks perfect on the external screen.

1. Dippi could have a "Detect screens" button which would load their information and auto-fill the information in the input fields
2. An "Apply" button would update the system config so that it applies the Dippi information. The usual window asking to keep or revert the changes would then appear.

With that, the app would be really powerful, and I would donate of course!

**Comment by cassidyjames** [comment] 2021-06-19 04:43
Dippi is just a specialized calculator and doesn't intend to change any settings. Otherwise this is a duplicate of #56

**Closed as completed by cassidyjames** 2021-06-19 04:43 UTC
