### ISSUE TITLE
3840×2160 at 24" shows as potentially problematic, though it should work fine at 2×

### ISSUE THREAD

**Issue by melix99** [cassidyjames/dippi#113] opened 2023-01-04 12:06 UTC
Hi, I wanted to try how Dippi feels about a 24" 3840x2160 desktop screen and the result is that it's potentially problematic:

![image](https://user-images.githubusercontent.com/23530586/210550696-778ef98b-b1e8-4ac9-a843-85a3a6db5946.png)

The problem is that if I set a resolution of 1920x1080 (half of 4k), it now says that it's ideal for LoDPI.

I didn't expect this result, because I think that the UI in a 24" 4k monitor with 200% scaling should appear just like the 1080p one, but maybe I'm just not considering something else? :)

**Comment by cassidyjames** [comment] 2023-01-09 17:31
Hmm, yeah, this is because GNOME (and elementary OS, at least) defaults to 192 DPI as the cutoff for HiDPI; this is just below that at 183 DPI, so by default, it would be at 1× scaling. I agree it would be better to handle, though, with a specific message about it working okay at 2× scaling.

I'll have to think about how to handle this.

**Comment by cassidyjames** [comment] 2023-01-09 17:37
Ah actually I'm going to consider this a duplicate of #112; it is the same underlying issue. Thanks for reporting, I'll aim to resolve this in the next release.

**Closed as completed by cassidyjames** 2023-01-09 17:37 UTC
Labels: Duplicate
